local variant = Tracker.ActiveVariantUID

-- Items
Tracker:AddItems("items/events.json")
Tracker:AddItems("items/events_hosted.json")
Tracker:AddItems("items/items.json")
Tracker:AddItems("items/items_hosted.json")
Tracker:AddItems("items/items_hosted_specific.json")
Tracker:AddItems("items/flyunlock.json")
Tracker:AddItems("items/settings.json")
Tracker:AddItems("items/settings_pokemon.json")
Tracker:AddItems("items/tools.json")
Tracker:AddItems("items/trainers.json")
Tracker:AddItems("items/pokemon.json")
Tracker:AddItems("items/dexsanity_visibility.json")
Tracker:AddItems("items/dexsanity_sent.json")

-- Logic
ScriptHost:LoadScript("scripts/logic/utils.lua")
ScriptHost:LoadScript("scripts/logic/utils_pokemon.lua")
ScriptHost:LoadScript("scripts/logic/logic.lua")
ScriptHost:LoadScript("scripts/logic/logic_pokemon.lua")
ScriptHost:LoadScript("scripts/custom_items.lua")

-- Maps
Tracker:AddMaps("maps/errors.json")
Tracker:AddMaps("maps/maps.json")
Tracker:AddMaps("maps/route212north_barriers.json")
Tracker:AddMaps("maps/route212north_unknown.json")
Tracker:AddMaps("maps/route214north_barriers.json")
Tracker:AddMaps("maps/route214north_unknown.json")
Tracker:AddMaps("maps/route210south_bike_slope.json")
Tracker:AddMaps("maps/route210south_bike_slope_cut.json")
Tracker:AddMaps("maps/route210south_bike_slope_psyduck.json")
Tracker:AddMaps("maps/route210south_bike_slope_rock_smash.json")
Tracker:AddMaps("maps/route210south_bike_slope_strength.json")
Tracker:AddMaps("maps/route210south_cut.json")
Tracker:AddMaps("maps/route210south_impassable.json")
Tracker:AddMaps("maps/route210south_psyduck.json")
Tracker:AddMaps("maps/route210south_rock_climb.json")
Tracker:AddMaps("maps/route210south_rock_climb_cut.json")
Tracker:AddMaps("maps/route210south_rock_climb_psyduck.json")
Tracker:AddMaps("maps/route210south_rock_climb_rock_smash.json")
Tracker:AddMaps("maps/route210south_rock_climb_strength.json")
Tracker:AddMaps("maps/route210south_rock_smash.json")
Tracker:AddMaps("maps/route210south_strength.json")
Tracker:AddMaps("maps/route210south_surf.json")
Tracker:AddMaps("maps/route210south_surf_cut.json")
Tracker:AddMaps("maps/route210south_surf_psyduck.json")
Tracker:AddMaps("maps/route210south_surf_rock_smash.json")
Tracker:AddMaps("maps/route210south_surf_strength.json")
Tracker:AddMaps("maps/route210south_waterfall.json")
Tracker:AddMaps("maps/route210south_waterfall_cut.json")
Tracker:AddMaps("maps/route210south_waterfall_psyduck.json")
Tracker:AddMaps("maps/route210south_waterfall_rock_smash.json")
Tracker:AddMaps("maps/route210south_waterfall_strength.json")
Tracker:AddMaps("maps/pokedex.json")

-- Layout
Tracker:AddLayouts("layouts/settings_popup.json")
Tracker:AddLayouts("layouts/items/items_hmreader_marshpass_storagekey_unownfile.json")
Tracker:AddLayouts("layouts/items/encounter_items.json")
Tracker:AddLayouts("layouts/items/evolution_items.json")
Tracker:AddLayouts("layouts/flyunlock.json")
Tracker:AddLayouts("layouts/events.json")
Tracker:AddLayouts("layouts/submaps.json")
Tracker:AddLayouts("layouts/pokedex.json")
Tracker:AddLayouts("layouts/tabs_single.json")
Tracker:AddLayouts("layouts/tracker.json")
Tracker:AddLayouts("layouts/broadcast.json")
Tracker:AddLayouts("layouts/quick_settings.json")
Tracker:AddLayouts("layouts/dexsearch.json")

-- Locations
Tracker:AddLocations("locations/access.jsonc")
Tracker:AddLocations("locations/overworldmap.jsonc")
Tracker:AddLocations("locations/submaps_singles.json")
Tracker:AddLocations("locations/submaps_groups.json")
Tracker:AddLocations("locations/submaps_encounters.json")
Tracker:AddLocations("locations/pokedex.json")
Tracker:AddLocations("locations/dexsanity.json")

-- AutoTracking for Poptracker
require("scripts/autotracking/archipelago")
require("scripts/toggles")
require("scripts/watches")
